#!/usr/bin/env node
/**
 * Turns a spreadsheet into the SQL that provisions a real class.
 *
 * V0 has no master screens: this script replaces them. Parv fills in one CSV,
 * this writes the inserts, and you run them against the right project.
 *
 *   node scripts/provision.mjs classes.csv > provision.sql
 *   # read provision.sql, then paste it into the Supabase SQL editor
 *
 * The CSV columns, header row required:
 *   institution,class,level,student_name,student_email,module_code,module_title,module_language,session_count
 *
 * One row per student. The class, institution and module repeat on every row of
 * that class — that is what makes the file easy to fill in by hand.
 *
 * It prints SQL and never connects to anything: nothing is provisioned until a
 * human reads the output and runs it. Student names and emails are personal
 * data, so the file you feed it does not belong in the repository.
 */

import { readFileSync } from 'node:fs'

const REQUIRED = [
  'institution',
  'class',
  'student_name',
  'student_email',
  'module_code',
  'module_title',
]

/** Minimal CSV reader: quoted fields, doubled quotes, commas and newlines inside them. */
function parseCsv(text) {
  const rows = []
  let row = []
  let field = ''
  let quoted = false

  for (let i = 0; i < text.length; i++) {
    const c = text[i]
    if (quoted) {
      if (c === '"') {
        if (text[i + 1] === '"') {
          field += '"'
          i++
        } else quoted = false
      } else field += c
    } else if (c === '"') quoted = true
    else if (c === ',') {
      row.push(field)
      field = ''
    } else if (c === '\n') {
      row.push(field)
      rows.push(row)
      row = []
      field = ''
    } else if (c !== '\r') field += c
  }
  if (field !== '' || row.length > 0) {
    row.push(field)
    rows.push(row)
  }
  return rows.filter((r) => r.some((cell) => cell.trim() !== ''))
}

const quote = (value) => `'${String(value).replace(/'/g, "''")}'`

function main() {
  const path = process.argv[2]
  if (!path) {
    console.error('Usage: node scripts/provision.mjs <file.csv> > provision.sql')
    process.exit(1)
  }

  const rows = parseCsv(readFileSync(path, 'utf8'))
  const header = rows.shift()?.map((h) => h.trim().toLowerCase())
  if (!header) {
    console.error('The file is empty.')
    process.exit(1)
  }

  const missing = REQUIRED.filter((column) => !header.includes(column))
  if (missing.length > 0) {
    console.error(`Missing column(s): ${missing.join(', ')}`)
    process.exit(1)
  }

  const records = rows.map((row) => Object.fromEntries(header.map((h, i) => [h, (row[i] ?? '').trim()])))

  const problems = []
  const seenEmails = new Map()
  records.forEach((record, i) => {
    const line = i + 2 // the header is line 1
    for (const column of REQUIRED) {
      if (!record[column]) problems.push(`line ${line}: ${column} is empty`)
    }
    if (record.student_email && !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(record.student_email)) {
      problems.push(`line ${line}: "${record.student_email}" does not look like an email`)
    }
    // The same address twice in one class would collide with the database's
    // unique (class_id, email) — better to hear it now than from a constraint.
    const key = `${record.class}|${record.student_email?.toLowerCase()}`
    if (seenEmails.has(key)) {
      problems.push(`line ${line}: ${record.student_email} is already in ${record.class} (line ${seenEmails.get(key)})`)
    } else seenEmails.set(key, line)
  })

  if (problems.length > 0) {
    console.error('Nothing was written. Fix these first:\n' + problems.map((p) => `  - ${p}`).join('\n'))
    process.exit(1)
  }

  const classes = new Map() // "institution|class" → { institution, name, level, students[] }
  const modules = new Map() // code → { code, title, language, sessionCount, classes:Set }

  for (const record of records) {
    const classKey = `${record.institution}|${record.class}`
    if (!classes.has(classKey)) {
      classes.set(classKey, {
        institution: record.institution,
        name: record.class,
        level: record.level || null,
        students: [],
      })
    }
    classes.get(classKey).students.push({ name: record.student_name, email: record.student_email })

    if (!modules.has(record.module_code)) {
      modules.set(record.module_code, {
        code: record.module_code,
        title: record.module_title,
        language: (record.module_language || 'en').toLowerCase(),
        sessionCount: Number(record.session_count || 0),
        classes: new Set(),
      })
    }
    modules.get(record.module_code).classes.add(classKey)
  }

  const out = []
  out.push('-- Generated by scripts/provision.mjs. Read it before you run it.')
  out.push(`-- ${classes.size} class(es), ${records.length} student profile(s), ${modules.size} module(s).`)
  out.push('-- Run it against ONE project (dev or prod), signed in as the master account.')
  out.push('begin;')
  out.push('')

  const classVar = (key) => `v_class_${[...classes.keys()].indexOf(key) + 1}`
  const moduleVar = (code) => `v_module_${[...modules.keys()].indexOf(code) + 1}`

  out.push('do $$')
  out.push('declare')
  for (const key of classes.keys()) out.push(`  ${classVar(key)} uuid;`)
  for (const code of modules.keys()) out.push(`  ${moduleVar(code)} uuid;`)
  out.push('  v_master uuid;')
  out.push('begin')
  out.push("  select id into v_master from public.staff_accounts where role = 'master' order by created_at limit 1;")
  out.push('')

  for (const [key, klass] of classes) {
    out.push(`  -- ${klass.institution} · ${klass.name}`)
    out.push('  insert into public.classes (name, institution, level, created_by)')
    out.push(
      `  values (${quote(klass.name)}, ${quote(klass.institution)}, ${klass.level ? quote(klass.level) : 'null'}, v_master)`,
    )
    out.push(`  returning id into ${classVar(key)};`)
    out.push('')
    for (const student of klass.students) {
      out.push('  insert into public.student_profiles (class_id, full_name, email)')
      out.push(`  values (${classVar(key)}, ${quote(student.name)}, ${quote(student.email)})`)
      out.push('  on conflict (class_id, email) do nothing;')
    }
    out.push('')
  }

  for (const [code, mod] of modules) {
    out.push(`  -- ${code} · ${mod.title}`)
    out.push('  insert into public.modules (code, title, language, session_count, created_by)')
    out.push(
      `  values (${quote(code)}, ${quote(mod.title)}, ${quote(mod.language)}, ${mod.sessionCount}, v_master)`,
    )
    out.push(`  returning id into ${moduleVar(code)};`)
    for (const classKey of mod.classes) {
      out.push('  insert into public.class_modules (class_id, module_id)')
      out.push(`  values (${classVar(classKey)}, ${moduleVar(code)}) on conflict do nothing;`)
    }
    out.push('')
  }

  out.push('end $$;')
  out.push('')
  out.push('commit;')
  out.push('')
  out.push('-- After this: sign in to Pulse as the master account, open the module,')
  out.push('-- write the entrance test and publish it. Students then create their')
  out.push('-- account with the exact address listed above — any other is refused.')

  console.log(out.join('\n'))
}

main()
